model_name: 'sd_xl'
batch_configs: [32,32,32]
locations: ['cuda:0','cuda:5','cuda:6']
lowvram_mode: False
dtype: 'half'
model: {
        "H": 1024,
        "W": 1024,
        "C": 4,
        "f": 8,
        "is_legacy": False,
        "config": "configs/inference/sd_xl_lora.yaml",
        "ckpt": "checkpoints/sd_xl_base_1.0.safetensors",
    }